### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by pplu** [barcelonapm/project-X#2]
A docker image is needed with the following:

 - Perl 5.24
 - Mojolicious

Would be great that cpanm would be available too (since deps can then be specified with a cpanfile)

**Comment by maneta** [comment]
iep! 

Please assign this issue to me. I have been out last weekend but I will be working on this during the holidays.

**Comment by pplu** [comment]
Don't know why, I can't, but it's all yours :smile:

**Comment by maneta** [comment]
Fair enough! :)  I will try have this done ASAP to unblock the development.

**Comment by maneta** [comment]
PR #5 Ready for Review.
