### ISSUE TITLE
One step registration

### ISSUE THREAD

**Issue by pplu** [barcelonapm/project-X#4]
Registration should be "one step".

Twitter and/or GitHub logins have been considered as good first targets. Although there are some concerns about if we will be able to have the users email so we can comunicate with him (although a valid alternative is if the platform let's you communicate with the user via their API)

Would be nice to have a "stub" application that just logs in to one of these services. Server code (if needed) would be nice as a Mojo app

**Comment by diegok** [comment]
Ok. I've just created the basic mojo-app to start doing some real work. I will create a login example using only the app session (cookie) and depending on external sources (fb, gh, google, ...). As you know, I would like to have another external source, so I'll start working on that option after this basic things are in place ;-)

**Comment by diegok** [comment]
OAUTH2 login with github, google and facebook is working. I've added a mechanismo to have routes that ensure a user is registered (or not) and basic user handling.

A "one step" registration will be trivial (when registration gets implemented) as it only need a route that goes thru the "enforce user logged in" mechanism.
